tap "thoughtbot/formulae"
tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "caskroom/fonts"
tap "caskroom/versions"
tap "caskroom/cask"
tap "neomutt/neomutt"

brew "ack"
brew "automake"
brew "bat"
brew "openssl"
brew "gdbm"
brew "readline"
brew "sqlite"
brew "python"
brew "python@2"
brew "awscli"
brew "bash"
brew "bison"
brew "chruby"
brew "coreutils"
brew "ctags"
brew "diff-so-fancy"
brew "diffutils"
brew "erlang"
brew "fasd"
brew "fontforge"
brew "fswatch"
brew "fzf"
brew "gem_home", args: ["HEAD"]
brew "git"
brew "git-crypt"
brew "libffi"
brew "gnupg", link: false
brew "go"
brew "gradle"
brew "graphviz"
brew "grc"
brew "grep", args: ["with-default-names"]
brew "highlight"
brew "imagemagick", args: ["with-x11"]
brew "jemalloc"
brew "jq"
brew "kafkacat"
brew "libuv"
brew "libyaml"
brew "luajit"
brew "lynx"
brew "markdown"
brew "mas"
brew "node"
brew "offlineimap"
brew "openssl@1.1"
brew "pandoc"
brew "postgresql"
brew "python"
brew "reattach-to-user-namespace"
brew "redis"
brew 'ripgrep'
brew "ruby-install"
brew "shellcheck"
brew "task"
brew "telnet"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "unrar"
brew "vim"
brew "watch"
brew "wget"
brew "yarn"
brew "z"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "zsh-completions"
brew "zsh-history-substring-search"
brew "neomutt/neomutt/neomutt"
brew "thoughtbot/formulae/rcm"

cask "java"
cask "karabiner-elements"
cask "caskroom/fonts/font-meslo-nerd-font"
cask "caskroom/fonts/font-meslo-nerd-font-mono"
cask "caskroom/versions/google-chrome-canary"
cask "xquartz"

mas "1Password 7", id: 1333542190
mas "Moom", id: 419330170
mas "Skitch", id: 425955336
