#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             first_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_shadow                on
yabai -m config window_border                off
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  21
yabai -m config bottom_padding               20
yabai -m config left_padding                 20
yabai -m config right_padding                20
yabai -m config window_gap                   20

yabai -m space 1 --label tools
yabai -m space 2 --label terminal
yabai -m space 3 --label web

# window rules

yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Installer" manage=off
yabai -m rule --add app="^Finder" manage=off
yabai -m rule --add app="^Dash" manage=off
yabai -m rule --add app="^Logi Options" manage=off

yabai -m rule --add app="^Mail$" space=tools
yabai -m rule --add app="^Slack$" space=tools
yabai -m rule --add app="^Messages$" space=tools
yabai -m rule --add app="^Trello$" space=tools
yabai -m rule --add app="^Safari$" space=web
yabai -m rule --add app="^Chrome$" space=web
yabai -m rule --add app="^Alacritty$" space=terminal

# signals
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

echo "yabai configuration loaded.."
